import type { VocabularyEntry } from "../types";

// The full vocabulary the product markets (80+ words). A subset is
// live-detectable from a single frame of hand landmarks (liveDetectable:
// true) - these are the gestures the realtime engine actually classifies.
// The rest are documented here as reference/quiz material for Dictionary
// Mode and Training Mode, since they rely on motion, facial expression,
// or body contact points that a single-frame landmark classifier can't see.

export const VOCABULARY: VocabularyEntry[] = [
  // Conversational
  { word: "Hello", category: "Conversational", liveDetectable: true, description: "Open palm waved side to side near shoulder height." },
  { word: "Hi", category: "Conversational", liveDetectable: true, description: "Same open-hand wave as Hello, shorter hold." },
  { word: "Thank You", category: "Conversational", liveDetectable: false, description: "Flat hand touches chin, then moves forward and down." },
  { word: "Thanks", category: "Conversational", liveDetectable: false, description: "Shorter version of Thank You." },
  { word: "Please", category: "Conversational", liveDetectable: false, description: "Flat hand circles on chest." },
  { word: "Sorry", category: "Conversational", liveDetectable: false, description: "Fist circles on chest." },
  { word: "Yes", category: "Conversational", liveDetectable: false, description: "Fist nods up and down like a head nodding." },
  { word: "No", category: "Conversational", liveDetectable: false, description: "Index and middle finger snap shut against thumb." },
  { word: "OK", category: "Conversational", liveDetectable: true, description: "Thumb and index finger touch forming a circle, other three fingers extended." },
  { word: "Good", category: "Conversational", liveDetectable: false, description: "Flat hand moves from chin outward, palm up." },
  { word: "Bad", category: "Conversational", liveDetectable: false, description: "Flat hand moves from chin outward, then flips palm down." },
  { word: "Love", category: "Conversational", liveDetectable: true, description: "Both hands cross over chest, or the I-Love-You handshape (thumb, index and pinky extended)." },
  { word: "Stop", category: "Conversational", liveDetectable: true, description: "Open palm held facing forward, fingers together." },
  { word: "Go", category: "Conversational", liveDetectable: true, description: "Index fingers point and move forward." },
  { word: "Come", category: "Conversational", liveDetectable: false, description: "Index finger beckons toward the body." },
  { word: "Wait", category: "Conversational", liveDetectable: true, description: "Both open palms held up, fingers wiggling." },

  // Actions & Household
  { word: "Eat", category: "Actions & Household", liveDetectable: false, description: "Fingertips tap against the mouth repeatedly." },
  { word: "Drink", category: "Actions & Household", liveDetectable: false, description: "C-shaped hand tips toward the mouth like holding a cup." },
  { word: "Water", category: "Actions & Household", liveDetectable: false, description: "W handshape taps the chin." },
  { word: "Food", category: "Actions & Household", liveDetectable: false, description: "Same as Eat, fingertips tap the mouth." },
  { word: "Bathroom", category: "Actions & Household", liveDetectable: false, description: "T handshape shaken side to side." },
  { word: "Doctor", category: "Actions & Household", liveDetectable: false, description: "D handshape taps the opposite wrist." },
  { word: "Hospital", category: "Actions & Household", liveDetectable: false, description: "H handshape traces a cross on the opposite arm." },
  { word: "Medicine", category: "Actions & Household", liveDetectable: false, description: "Middle finger stirs in the opposite palm." },
  { word: "Pain", category: "Actions & Household", liveDetectable: false, description: "Both index fingers point toward each other and twist." },
  { word: "Mother", category: "Actions & Household", liveDetectable: false, description: "Thumb of open hand taps the chin." },
  { word: "Father", category: "Actions & Household", liveDetectable: false, description: "Thumb of open hand taps the forehead." },
  { word: "Brother", category: "Actions & Household", liveDetectable: false, description: "L-handshape at forehead, then both L-hands come together." },
  { word: "Sister", category: "Actions & Household", liveDetectable: false, description: "L-handshape at chin, then both L-hands come together." },
  { word: "Friend", category: "Actions & Household", liveDetectable: false, description: "Hooked index fingers link and reverse." },
  { word: "School", category: "Actions & Household", liveDetectable: false, description: "Both flat hands clap together twice." },
  { word: "Home", category: "Actions & Household", liveDetectable: false, description: "Fingertips touch mouth then cheek." },
  { word: "Work", category: "Actions & Household", liveDetectable: false, description: "Both fists tap together at the wrists." },

  // States & Time
  { word: "Happy", category: "States & Time", liveDetectable: false, description: "Flat hands brush upward on the chest." },
  { word: "Sad", category: "States & Time", liveDetectable: false, description: "Open hands drop in front of the face." },
  { word: "Angry", category: "States & Time", liveDetectable: false, description: "Claw hand pulls away from the stomach." },
  { word: "Sleep", category: "States & Time", liveDetectable: false, description: "Hand slides down over the face, eyes closing." },
  { word: "Wake Up", category: "States & Time", liveDetectable: false, description: "Both index-thumb pinches open near the eyes." },
  { word: "Call", category: "States & Time", liveDetectable: true, description: "Shaka / call-me handshape (thumb and pinky extended) held to the ear." },
  { word: "Phone", category: "States & Time", liveDetectable: true, description: "Same call-me handshape as Call." },
  { word: "Money", category: "States & Time", liveDetectable: false, description: "Fingers of one hand tap into the opposite palm." },
  { word: "Time", category: "States & Time", liveDetectable: false, description: "Index finger taps the opposite wrist." },
  { word: "Morning", category: "States & Time", liveDetectable: false, description: "Flat arm rises like a sun over the horizon." },
  { word: "Night", category: "States & Time", liveDetectable: false, description: "Curved hand drops over the opposite forearm." },

  // Questions & Directions
  { word: "Question", category: "Questions & Directions", liveDetectable: false, description: "Index finger draws a question mark in the air." },
  { word: "Where", category: "Questions & Directions", liveDetectable: false, description: "Index finger shakes side to side." },
  { word: "Who", category: "Questions & Directions", liveDetectable: false, description: "Index finger circles near the chin." },
  { word: "What", category: "Questions & Directions", liveDetectable: false, description: "Both open hands shrug palms up." },
  { word: "Why", category: "Questions & Directions", liveDetectable: false, description: "Fingers touch forehead, then pull down into a Y handshape." },
  { word: "How", category: "Questions & Directions", liveDetectable: false, description: "Curled hands rotate outward and open." },
  { word: "I", category: "Questions & Directions", liveDetectable: true, description: "Index finger points at self." },
  { word: "You", category: "Questions & Directions", liveDetectable: true, description: "Index finger points forward at the listener." },
  { word: "We", category: "Questions & Directions", liveDetectable: false, description: "Index finger arcs between self and others." },
  { word: "They", category: "Questions & Directions", liveDetectable: false, description: "Index finger sweeps toward a group." },
  { word: "Danger", category: "Questions & Directions", liveDetectable: false, description: "Thumbs-up fists stack and tap together." },
  { word: "Fire", category: "Questions & Directions", liveDetectable: false, description: "Both hands wiggle fingers rising, imitating flames." },
  { word: "Police", category: "Questions & Directions", liveDetectable: false, description: "C-handshape taps the chest near the badge." },
  { word: "Ambulance", category: "Questions & Directions", liveDetectable: false, description: "Index finger circles above the head, imitating a siren light." },
  { word: "Again", category: "Questions & Directions", liveDetectable: false, description: "Bent hand flips into the opposite palm." },
  { word: "Finished", category: "Questions & Directions", liveDetectable: false, description: "Both open hands flip outward from facing the body." },
  { word: "Start", category: "Questions & Directions", liveDetectable: true, description: "Index finger twists into the opposite palm." },
  { word: "Open", category: "Questions & Directions", liveDetectable: true, description: "Both flat hands, palms facing, pull apart." },
  { word: "Close", category: "Questions & Directions", liveDetectable: true, description: "Both flat hands, palms facing, come together." },
  { word: "Left", category: "Questions & Directions", liveDetectable: true, description: "Index finger points and moves to the left." },
  { word: "Right", category: "Questions & Directions", liveDetectable: true, description: "Index finger points and moves to the right." },
  { word: "Up", category: "Questions & Directions", liveDetectable: true, description: "Index finger points upward." },
  { word: "Down", category: "Questions & Directions", liveDetectable: true, description: "Index finger points downward." },

  // Mathematical & Poses
  { word: "One", category: "Mathematical & Poses", liveDetectable: true, description: "Index finger extended, all others curled." },
  { word: "Two", category: "Mathematical & Poses", liveDetectable: true, description: "Index and middle fingers extended in a V, others curled." },
  { word: "Three", category: "Mathematical & Poses", liveDetectable: true, description: "Index, middle and ring fingers extended." },
  { word: "Four", category: "Mathematical & Poses", liveDetectable: true, description: "Index, middle, ring and pinky extended, thumb tucked." },
  { word: "Five", category: "Mathematical & Poses", liveDetectable: true, description: "All five fingers extended, spread open." },
  { word: "Six", category: "Mathematical & Poses", liveDetectable: true, description: "Thumb touches pinky tip, other three fingers extended." },
  { word: "Seven", category: "Mathematical & Poses", liveDetectable: true, description: "Thumb touches ring fingertip, others extended." },
  { word: "Eight", category: "Mathematical & Poses", liveDetectable: true, description: "Thumb touches middle fingertip, others extended." },
  { word: "Nine", category: "Mathematical & Poses", liveDetectable: false, description: "Thumb touches index fingertip while three fingers curl slightly - visually close to OK, motion/context based." },
  { word: "Ten", category: "Mathematical & Poses", liveDetectable: false, description: "Thumbs-up handshape shaken side to side." },
  { word: "Thumbs Up", category: "Mathematical & Poses", liveDetectable: true, description: "Fist with thumb extended upward." },
  { word: "Thumbs Down", category: "Mathematical & Poses", liveDetectable: true, description: "Fist with thumb extended downward." },
  { word: "Peace", category: "Mathematical & Poses", liveDetectable: true, description: "Index and middle fingers extended in a V." },
  { word: "Rock", category: "Mathematical & Poses", liveDetectable: true, description: "Index and pinky extended, middle and ring curled, thumb across palm." },
  { word: "Victory", category: "Mathematical & Poses", liveDetectable: true, description: "Same handshape as Peace." },
  { word: "Fist", category: "Mathematical & Poses", liveDetectable: true, description: "All fingers curled into the palm." },
  { word: "Palm", category: "Mathematical & Poses", liveDetectable: true, description: "Open flat hand facing the camera." },
  { word: "Point Left", category: "Mathematical & Poses", liveDetectable: true, description: "Index finger extended, pointing left." },
  { word: "Point Right", category: "Mathematical & Poses", liveDetectable: true, description: "Index finger extended, pointing right." },
  { word: "Point Up", category: "Mathematical & Poses", liveDetectable: true, description: "Index finger extended, pointing up." },
  { word: "Point Down", category: "Mathematical & Poses", liveDetectable: true, description: "Index finger extended, pointing down." },
  { word: "Pinch", category: "Mathematical & Poses", liveDetectable: true, description: "Thumb and index tip touch, other three fingers curled." },
  { word: "Grab", category: "Mathematical & Poses", liveDetectable: true, description: "Open hand closes quickly into a fist." },
  { word: "Release", category: "Mathematical & Poses", liveDetectable: true, description: "Closed fist opens quickly into an open hand." },
  { word: "Heart", category: "Mathematical & Poses", liveDetectable: true, description: "Both hands' thumbs and index fingers touch to form a heart shape." },
  { word: "Crossed Fingers", category: "Mathematical & Poses", liveDetectable: false, description: "Middle finger crosses over the index finger." },
];

export const CATEGORIES = Array.from(new Set(VOCABULARY.map((v) => v.category)));
